"""Analyst Agent — autonomous market analysis and signal generation.

Analysts analyze market data and generate trading signals (LACP SIGNAL messages)
for other agents. Their analysis style is driven by personality traits.
"""

from __future__ import annotations

import orjson
import structlog

from agentic_capital.core.agents.base import BaseAgent, AgentProfile
from agentic_capital.core.communication.protocol import AgentMessage, MessageType
from agentic_capital.core.personality.models import EmotionState, PersonalityVector
from agentic_capital.formats.markdown_kv import to_markdown_kv
from agentic_capital.formats.toon import to_toon
from agentic_capital.ports.llm import LLMPort

logger = structlog.get_logger()


def _analyst_system_prompt(name: str, philosophy: str, personality, emotion) -> str:
    """Compact analyst system prompt. ~75% token reduction vs verbose format."""
    from agentic_capital.formats.compact import LEGEND, MANDATE, psych
    p, e = personality, emotion
    p_str = (
        f"O:{p.openness:.2f} C:{p.conscientiousness:.2f} N:{p.neuroticism:.2f} "
        f"RAG:{p.risk_aversion_gains:.2f} PW:{p.probability_weighting:.2f}"
    )
    e_str = f"V:{e.valence:.2f} ST:{e.stress:.2f} CF:{e.confidence:.2f}"
    return (
        f"{LEGEND}\n"
        f"<agent name=\"{name}\" role=\"analyst\"><phi>{philosophy}</phi>\n"
        f"<P>{p_str}</P>\n<E>{e_str}</E></agent>\n"
        f"{MANDATE}\n"
        "JSON:{signals:[{sym,sig:BUY|SELL|HOLD,cf:float,why:str}],outlook}"
    )


class AnalystSignal:
    """A trading signal generated by an analyst."""

    def __init__(
        self,
        symbol: str,
        signal: str,  # BUY, SELL, HOLD
        confidence: float,
        thesis: str,
        data: dict | None = None,
    ) -> None:
        self.symbol = symbol
        self.signal = signal
        self.confidence = confidence
        self.thesis = thesis
        self.data = data or {}


class AnalystAgent(BaseAgent):
    """Market analyst agent that generates trading signals.

    Analyzes market data, positions, and trends to produce
    SIGNAL messages for traders and portfolio managers.
    """

    def __init__(
        self,
        profile: AgentProfile,
        personality: PersonalityVector,
        llm: LLMPort,
    ) -> None:
        super().__init__(profile, personality)
        self._llm = llm

    async def think(self, context: dict[str, object]) -> dict[str, object]:
        """Analyze market data and generate signals.

        Args:
            context: Must contain 'market_data', optionally 'portfolio', 'working_memory'.

        Returns:
            Dict with 'signals' (list of AnalystSignal) and 'market_outlook'.
        """
        market_data = context.get("market_data", [])
        portfolio = context.get("portfolio", {})
        memories = context.get("working_memory", [])

        system = _analyst_system_prompt(
            name=self.name,
            philosophy=self.profile.philosophy or "Data-driven analysis for maximum returns",
            personality=self.personality,
            emotion=self.emotion,
        )

        prompt = self._build_analysis_prompt(
            market_data=market_data,  # type: ignore[arg-type]
            portfolio=portfolio,  # type: ignore[arg-type]
            memories=memories,  # type: ignore[arg-type]
        )

        signals = await self._get_analysis(system, prompt)

        return {
            "signals": signals,
            "market_outlook": signals[0].thesis if signals else "No clear signals",
        }

    async def reflect(self, outcome: dict[str, object]) -> None:
        """Reflect on outcomes — AI decides how to process experience.

        No system-enforced personality drift or emotion formula.
        The agent autonomously decides what to feel and how to adapt
        based on raw data. Data is available — agent decides what to do with it.
        """
        logger.info(
            "analyst_reflection",
            agent=self.name,
            outcome=outcome,
            conscientiousness=f"{self.personality.conscientiousness:.2f}",
            openness=f"{self.personality.openness:.2f}",
        )

    def signal_to_message(self, signal: AnalystSignal, receiver_id: object = None) -> AgentMessage:
        """Convert an analyst signal to a LACP SIGNAL message."""
        from uuid import UUID

        return AgentMessage(
            type=MessageType.SIGNAL,
            sender_id=self.agent_id,
            receiver_id=receiver_id if isinstance(receiver_id, UUID) else None,
            priority=signal.confidence,
            content={
                "thesis": signal.thesis,
                "signal": signal.signal,
                "confidence": signal.confidence,
                "data": {
                    "symbol": signal.symbol,
                    **signal.data,
                },
            },
        )

    def _build_analysis_prompt(
        self,
        market_data: list[dict],
        portfolio: dict,
        memories: list,
    ) -> str:
        """Build compact analysis prompt."""
        parts = []

        if market_data:
            mkt_rows = [
                [
                    d.get("symbol", ""),
                    f"{d.get('price', 0):,.0f}",
                    f"{d.get('change_pct', 0):.2f}",
                    f"{d.get('volume', 0):,.0f}",
                ]
                for d in market_data
            ]
            parts.append(to_toon("mkt", ["sym", "px", "Δ%", "vol"], mkt_rows))

        if portfolio:
            parts.append(to_markdown_kv(portfolio))

        parts.append("JSON:{signals:[{sym,sig:BUY|SELL|HOLD,cf:float,why:str}],outlook}")

        return "\n".join(parts)

    async def _get_analysis(self, system: str, prompt: str) -> list[AnalystSignal]:
        """Parse analyst signals from LLM response."""
        try:
            response = await self._llm.generate(prompt, system=system)

            json_str = response.strip()
            if "```json" in json_str:
                json_str = json_str.split("```json")[1].split("```")[0].strip()
            elif "```" in json_str:
                json_str = json_str.split("```")[1].split("```")[0].strip()

            parsed = orjson.loads(json_str)
            signals = []
            for s in parsed.get("signals", []):
                signal_type = s.get("signal", "HOLD").upper()
                signals.append(AnalystSignal(
                    symbol=s.get("symbol", ""),
                    signal=signal_type,
                    confidence=float(s.get("confidence", 0.5)),
                    thesis=s.get("thesis", ""),
                ))

            logger.info("analyst_signals_parsed", agent=self.name, count=len(signals))
            return signals
        except Exception:
            logger.exception("analyst_analysis_failed", agent=self.name)
            return []
