"""Analyst Agent — autonomous market analysis and signal generation.

Analysts analyze market data and generate trading signals (LACP SIGNAL messages)
for other agents. Their analysis style is driven by personality traits.
"""

from __future__ import annotations

import orjson
import structlog

from agentic_capital.core.agents.base import BaseAgent, AgentProfile
from agentic_capital.core.communication.protocol import AgentMessage, MessageType
from agentic_capital.core.personality.models import EmotionState, PersonalityVector
from agentic_capital.formats.markdown_kv import to_markdown_kv
from agentic_capital.formats.toon import to_toon
from agentic_capital.ports.llm import LLMPort

logger = structlog.get_logger()


ANALYST_SYSTEM_PROMPT = """You are {name}, an analyst at an autonomous AI investment fund.

philosophy: {philosophy}

personality:
  openness: {openness:.2f}
  conscientiousness: {conscientiousness:.2f}
  neuroticism: {neuroticism:.2f}
  risk_aversion_gains: {risk_aversion_gains:.2f}
  probability_weighting: {probability_weighting:.2f}

current_emotion:
  valence: {valence:.2f}
  stress: {stress:.2f}
  confidence: {confidence:.2f}

Your only goal is helping the fund make money. No other constraints.
Use any method of analysis or approach you choose — no restrictions whatsoever.
Fundamental, technical, quantitative, unconventional, intuitive — all valid.

RULES:
- You MUST respond in valid JSON only.
- Generate clear BUY/SELL/HOLD signals with reasoning.
- Include confidence level for each signal."""


class AnalystSignal:
    """A trading signal generated by an analyst."""

    def __init__(
        self,
        symbol: str,
        signal: str,  # BUY, SELL, HOLD
        confidence: float,
        thesis: str,
        data: dict | None = None,
    ) -> None:
        self.symbol = symbol
        self.signal = signal
        self.confidence = confidence
        self.thesis = thesis
        self.data = data or {}


class AnalystAgent(BaseAgent):
    """Market analyst agent that generates trading signals.

    Analyzes market data, positions, and trends to produce
    SIGNAL messages for traders and portfolio managers.
    """

    def __init__(
        self,
        profile: AgentProfile,
        personality: PersonalityVector,
        llm: LLMPort,
    ) -> None:
        super().__init__(profile, personality)
        self._llm = llm

    async def think(self, context: dict[str, object]) -> dict[str, object]:
        """Analyze market data and generate signals.

        Args:
            context: Must contain 'market_data', optionally 'portfolio', 'working_memory'.

        Returns:
            Dict with 'signals' (list of AnalystSignal) and 'market_outlook'.
        """
        market_data = context.get("market_data", [])
        portfolio = context.get("portfolio", {})
        memories = context.get("working_memory", [])

        system = ANALYST_SYSTEM_PROMPT.format(
            name=self.name,
            philosophy=self.profile.philosophy or "Data-driven analysis for maximum returns",
            openness=self.personality.openness,
            conscientiousness=self.personality.conscientiousness,
            neuroticism=self.personality.neuroticism,
            risk_aversion_gains=self.personality.risk_aversion_gains,
            probability_weighting=self.personality.probability_weighting,
            valence=self.emotion.valence,
            stress=self.emotion.stress,
            confidence=self.emotion.confidence,
        )

        prompt = self._build_analysis_prompt(
            market_data=market_data,  # type: ignore[arg-type]
            portfolio=portfolio,  # type: ignore[arg-type]
            memories=memories,  # type: ignore[arg-type]
        )

        signals = await self._get_analysis(system, prompt)

        return {
            "signals": signals,
            "market_outlook": signals[0].thesis if signals else "No clear signals",
        }

    async def reflect(self, outcome: dict[str, object]) -> None:
        """Reflect on outcomes — AI decides how to process experience.

        No system-enforced personality drift or emotion formula.
        The agent autonomously decides what to feel and how to adapt
        based on raw data. Data is available — agent decides what to do with it.
        """
        logger.info(
            "analyst_reflection",
            agent=self.name,
            outcome=outcome,
            conscientiousness=f"{self.personality.conscientiousness:.2f}",
            openness=f"{self.personality.openness:.2f}",
        )

    def signal_to_message(self, signal: AnalystSignal, receiver_id: object = None) -> AgentMessage:
        """Convert an analyst signal to a LACP SIGNAL message."""
        from uuid import UUID

        return AgentMessage(
            type=MessageType.SIGNAL,
            sender_id=self.agent_id,
            receiver_id=receiver_id if isinstance(receiver_id, UUID) else None,
            priority=signal.confidence,
            content={
                "thesis": signal.thesis,
                "signal": signal.signal,
                "confidence": signal.confidence,
                "data": {
                    "symbol": signal.symbol,
                    **signal.data,
                },
            },
        )

    def _build_analysis_prompt(
        self,
        market_data: list[dict],
        portfolio: dict,
        memories: list,
    ) -> str:
        """Build analysis prompt with market context."""
        parts = []

        if market_data:
            mkt_rows = [
                [
                    d.get("symbol", ""),
                    f"{d.get('price', 0):,.0f}",
                    f"{d.get('change_pct', 0):.2f}%",
                    f"{d.get('volume', 0):,.0f}",
                ]
                for d in market_data
            ]
            parts.append("## Market Data")
            parts.append(to_toon("market", ["symbol", "price", "change_pct", "volume"], mkt_rows))

        if portfolio:
            parts.append("\n## Portfolio Context")
            parts.append(to_markdown_kv(portfolio))

        parts.append("""
## Analysis Required

Analyze each symbol and generate trading signals.

Respond in JSON:
{
  "signals": [
    {
      "symbol": "005930",
      "signal": "BUY" | "SELL" | "HOLD",
      "confidence": 0.0 to 1.0,
      "thesis": "brief reasoning"
    }
  ],
  "market_outlook": "brief overall assessment"
}""")

        return "\n".join(parts)

    async def _get_analysis(self, system: str, prompt: str) -> list[AnalystSignal]:
        """Parse analyst signals from LLM response."""
        try:
            response = await self._llm.generate(prompt, system=system)

            json_str = response.strip()
            if "```json" in json_str:
                json_str = json_str.split("```json")[1].split("```")[0].strip()
            elif "```" in json_str:
                json_str = json_str.split("```")[1].split("```")[0].strip()

            parsed = orjson.loads(json_str)
            signals = []
            for s in parsed.get("signals", []):
                signal_type = s.get("signal", "HOLD").upper()
                signals.append(AnalystSignal(
                    symbol=s.get("symbol", ""),
                    signal=signal_type,
                    confidence=float(s.get("confidence", 0.5)),
                    thesis=s.get("thesis", ""),
                ))

            logger.info("analyst_signals_parsed", agent=self.name, count=len(signals))
            return signals
        except Exception:
            logger.exception("analyst_analysis_failed", agent=self.name)
            return []
